//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FirewallApp.Data
{

    public partial class RuleModel : XPObject
    {
        string fDisplayName;
        [Size(SizeAttribute.Unlimited)]
        public string DisplayName
        {
            get { return fDisplayName; }
            set { SetPropertyValue<string>(nameof(DisplayName), ref fDisplayName, value); }
        }
        string fDescription;
        [Size(SizeAttribute.Unlimited)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        string fDisplayGroup;
        [Size(SizeAttribute.Unlimited)]
        public string DisplayGroup
        {
            get { return fDisplayGroup; }
            set { SetPropertyValue<string>(nameof(DisplayGroup), ref fDisplayGroup, value); }
        }
        string fInstanceID;
        public string InstanceID
        {
            get { return fInstanceID; }
            set { SetPropertyValue<string>(nameof(InstanceID), ref fInstanceID, value); }
        }
        string fAction;
        public string Action
        {
            get { return fAction; }
            set { SetPropertyValue<string>(nameof(Action), ref fAction, value); }
        }
        string fEnabled;
        public string Enabled
        {
            get { return fEnabled; }
            set { SetPropertyValue<string>(nameof(Enabled), ref fEnabled, value); }
        }
        string fDirection;
        public string Direction
        {
            get { return fDirection; }
            set { SetPropertyValue<string>(nameof(Direction), ref fDirection, value); }
        }
        string fEdgeTraversalPolicy;
        public string EdgeTraversalPolicy
        {
            get { return fEdgeTraversalPolicy; }
            set { SetPropertyValue<string>(nameof(EdgeTraversalPolicy), ref fEdgeTraversalPolicy, value); }
        }
        string fPrimaryStatus;
        public string PrimaryStatus
        {
            get { return fPrimaryStatus; }
            set { SetPropertyValue<string>(nameof(PrimaryStatus), ref fPrimaryStatus, value); }
        }
        string fInterfaceType;
        public string InterfaceType
        {
            get { return fInterfaceType; }
            set { SetPropertyValue<string>(nameof(InterfaceType), ref fInterfaceType, value); }
        }
        string fProgram;
        public string Program
        {
            get { return fProgram; }
            set { SetPropertyValue<string>(nameof(Program), ref fProgram, value); }
        }
        string fLocalAddress;
        public string LocalAddress
        {
            get { return fLocalAddress; }
            set { SetPropertyValue<string>(nameof(LocalAddress), ref fLocalAddress, value); }
        }
        string fRemoteAddress;
        public string RemoteAddress
        {
            get { return fRemoteAddress; }
            set { SetPropertyValue<string>(nameof(RemoteAddress), ref fRemoteAddress, value); }
        }
        string fLocalPort;
        public string LocalPort
        {
            get { return fLocalPort; }
            set { SetPropertyValue<string>(nameof(LocalPort), ref fLocalPort, value); }
        }
        string fRemotePort;
        public string RemotePort
        {
            get { return fRemotePort; }
            set { SetPropertyValue<string>(nameof(RemotePort), ref fRemotePort, value); }
        }
        string fProtocol;
        public string Protocol
        {
            get { return fProtocol; }
            set { SetPropertyValue<string>(nameof(Protocol), ref fProtocol, value); }
        }
        string fProfile;
        public string Profile
        {
            get { return fProfile; }
            set { SetPropertyValue<string>(nameof(Profile), ref fProfile, value); }
        }
    }

}
