//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FirewallApp.Data
{

    public partial class FirewallRule : XPObject
    {
        string fElementName;
        public string ElementName
        {
            get { return fElementName; }
            set { SetPropertyValue<string>(nameof(ElementName), ref fElementName, value); }
        }
        string fDisplayName;
        public string DisplayName
        {
            get { return fDisplayName; }
            set { SetPropertyValue<string>(nameof(DisplayName), ref fDisplayName, value); }
        }
        string fDescription;
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        string fDirection;
        public string Direction
        {
            get { return fDirection; }
            set { SetPropertyValue<string>(nameof(Direction), ref fDirection, value); }
        }
        string fEnabled;
        public string Enabled
        {
            get { return fEnabled; }
            set { SetPropertyValue<string>(nameof(Enabled), ref fEnabled, value); }
        }
        string fProgram;
        public string Program
        {
            get { return fProgram; }
            set { SetPropertyValue<string>(nameof(Program), ref fProgram, value); }
        }
        string fLocalAddress;
        public string LocalAddress
        {
            get { return fLocalAddress; }
            set { SetPropertyValue<string>(nameof(LocalAddress), ref fLocalAddress, value); }
        }
        string fLocalPort;
        public string LocalPort
        {
            get { return fLocalPort; }
            set { SetPropertyValue<string>(nameof(LocalPort), ref fLocalPort, value); }
        }
        string fRemoteAddress;
        public string RemoteAddress
        {
            get { return fRemoteAddress; }
            set { SetPropertyValue<string>(nameof(RemoteAddress), ref fRemoteAddress, value); }
        }
        string fRemotePort;
        public string RemotePort
        {
            get { return fRemotePort; }
            set { SetPropertyValue<string>(nameof(RemotePort), ref fRemotePort, value); }
        }
    }

}
