//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FirewallApp.Data
{

    public partial class FirewallRule : XPObject
    {
        string fElementName;
        public string ElementName
        {
            get { return fElementName; }
            set { SetPropertyValue<string>(nameof(ElementName), ref fElementName, value); }
        }
        string fDisplayName;
        public string DisplayName
        {
            get { return fDisplayName; }
            set { SetPropertyValue<string>(nameof(DisplayName), ref fDisplayName, value); }
        }
        string fDescription;
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        string fDirection;
        public string Direction
        {
            get { return fDirection; }
            set { SetPropertyValue<string>(nameof(Direction), ref fDirection, value); }
        }
        bool fEnabled;
        public bool Enabled
        {
            get { return fEnabled; }
            set { SetPropertyValue<bool>(nameof(Enabled), ref fEnabled, value); }
        }
    }

}
